# Generated by Django 5.0 on 2023-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessdost_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgoalquestionnaire',
            name='desired_outcome',
        ),
        migrations.RemoveField(
            model_name='fitnessgoalquestionnaire',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='fitnessgoalquestionnaire',
            name='health_conditions',
        ),
        migrations.RemoveField(
            model_name='fitnessgoalquestionnaire',
            name='workout_intensity_preference',
        ),
        migrations.AddField(
            model_name='fitnessgoalquestionnaire',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessgoalquestionnaire',
            name='goal',
            field=models.CharField(choices=[('B', 'Lose Weight'), ('I', 'Gain Weight'), ('A', 'Gain Muscle Mass')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='fitnessgoalquestionnaire',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessgoalquestionnaire',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
