# Generated by Django 5.0 on 2023-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessdost_app', '0002_remove_fitnessgoalquestionnaire_desired_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgoalquestionnaire',
            name='current_fitness_level',
        ),
        migrations.RemoveField(
            model_name='fitnessgoalquestionnaire',
            name='user',
        ),
        migrations.AlterField(
            model_name='fitnessgoalquestionnaire',
            name='goal',
            field=models.CharField(choices=[('L', 'Lose Weight'), ('G', 'Gain Weight'), ('G', 'Gain Muscle Mass'), ('O', 'Other')], default='L', max_length=2),
        ),
    ]
